# Generated by Django 4.2.15 on 2024-09-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                default="http://127.0.0.1:8000/media/products/images/PolishLodyLogo.jpg",
                null=True,
                upload_to="products/images/",
            ),
        ),
    ]
