# Generated by Django 4.2.15 on 2024-09-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                default="products/images/PolishLodyLogo.jpg",
                null=True,
                upload_to="products/images/",
            ),
        ),
    ]
